# Kanagawa Dragon Palette
set -g @thm_bg "#181616"
set -g @thm_fg "#c5c9c5"
set -g @thm_border "#1D2021"
set -g @thm_blue "#8ba4b0"
set -g @thm_purple "#a292a3"
set -g @thm_red "#c4746e"
set -g @thm_green "#8a9a7b"
set -g @thm_yellow "#c4b28a"
set -g @thm_cyan "#8ea4a2"
set -g @thm_grey "#727169"
set -g @thm_lavender "#957fb8"
