# Catppuccin Mocha Palette
set -g @thm_bg "#1e1e2e"
set -g @thm_fg "#cdd6f4"
set -g @thm_border "#45475a"
set -g @thm_blue "#89b4fa"
set -g @thm_purple "#cba6f7"
set -g @thm_red "#f38ba8"
set -g @thm_green "#a6e3a1"
set -g @thm_yellow "#f9e2af"
set -g @thm_cyan "#94e2d5"
set -g @thm_grey "#6c7086"
