source-file ~/.config/tmux-config/colors.conf
source-file ~/.config/tmux-config/components/battery.conf
source-file ~/.config/tmux-config/components/cpu.conf
source-file ~/.config/tmux-config/components/ram.conf

set -g status-style "bg=#{@thm_bg},fg=#{@thm_fg}"
set -g status-left "#[fg=#{@thm_blue},bold] #S "

# set -g status-right "#( ~/.config/tmux-config/scripts/cpu.sh ) #[fg=#{@thm_red}] #[default]  #( ~/.config/tmux-config/scripts/battery.sh ) #[fg=#{@thm_green}]🔋 "

set -g status-justify left
set -s escape-time 0
set -g repeat-time 180
set -g status-left-length 200
set -g status-right-length 200
set -g status-style "fg=#{@thm_fg},bg=none"
# set -g status-justify absolute-centre
set -g status-justify left

set -g message-style "fg=#{@thm_border},bg=#{@thm_cyan}"

set -g status-left ""
# set -ag status-left "#[fg=#{?client_prefix,#{@thm_red},#{@thm_fg}},bg=#{@thm_border}]  #[fg=#{@thm_fg}, bold]#S "
# set -ag status-left ""

setw -g window-status-separator ""
setw -g window-status-format "#[fg=#{@thm_fg},bg=#{@thm_grey}] #I #[fg=#{@thm_fg},bg=#{@thm_border}] #W "
setw -g window-status-current-format "#[fg=#{@thm_bg},bg=#{@thm_purple}] #I #[fg=#{@thm_fg},bg=#{@thm_border}] #W "

set -g status-right ""
#set -ag status-right "%a, %d %b | %H:%M "
set -ag status-right "#{E:@ram_component} #{E:@cpu_component} #{E:@battery_component}"
set -ag status-right ""

