source-file ~/.config/tmux-config/colors.conf
source-file ~/.config/tmux-config/components/battery.conf
source-file ~/.config/tmux-config/components/cpu.conf
source-file ~/.config/tmux-config/components/ram.conf
source-file ~/.config/tmux-config/components/wifi.conf

# General Status Bar Settings
set -g status-interval 3
set -g status-justify absolute-centre
set -g status-style "fg=#{@thm_fg},bg=default"

# Left Side: Session Name
set -g status-left-length 100
set -g status-left ""
set -ag status-left "#{E:@wifi_component} #{E:@ram_component}"
# set -ag status-left "#[fg=#{@thm_bg},bg=#{@thm_blue},bold]  #S #[fg=#{@thm_blue},bg=default]"

# Right Side: System Stats & Time
set -g status-right-length 100
set -g status-right ""
set -ag status-right "#{E:@cpu_component} #{E:@battery_component}"
set -ag status-right ""

# Window Status
setw -g window-status-separator "  "
setw -g window-status-format "#[fg=#{@thm_grey},bg=default]#I #W"
setw -g window-status-current-format "#[fg=#{@thm_red}]#I #W"

# Messages
set -g message-style "fg=#{@thm_bg},bg=#{@thm_purple},bold"
