source-file ~/.config/tmux-config/colors.conf
# source-file ~/.config/tmux-config/components/battery.conf
# source-file ~/.config/tmux-config/components/cpu.conf
# source-file ~/.config/tmux-config/components/ram.conf
# source-file ~/.config/tmux-config/components/wifi.conf

# General Status Bar Settings
set -g status-interval 3
set -g status-justify left 
# set -g status-justify absolute-centre
set -g status-style "fg=#{@thm_fg},bg=default"

# Left Side: Session Name
set -g status-left-length 100
set -g status-left " "
# Right Side: System Stats & Time
set -g status-right-length 100
set -g status-right ""
# set -ag status-right "#{E:@cpu_component} #{E:@battery_component} "
# set -ag status-right "#{E:@wifi_component} #{E:@ram_component}"
# set -ag status-right "#[fg=#{@thm_bg},bg=#{@thm_blue},bold]  #S #[fg=#{@thm_blue},bg=default]"
# set -ag status-right " "

# Window Status
setw -g window-status-separator "  "
setw -g window-status-format "#[fg=#{@thm_window},bg=default]#W"
setw -g window-status-current-format "#[fg=#{@thm_window_active}]#W"

# Messages
set -g message-style "fg=#{@thm_bg},bg=#{@thm_window_active},bold"
