vim.o.termguicolors = true -- use terminal colors
vim.o.showmode = false -- show mode in statusbar
vim.wo.number = true -- show numbers aside
vim.o.relativenumber = true -- show numbers relative to current line
vim.o.signcolumn = "yes"
vim.o.statuscolumn = [[%s%=%@v:relnum@%{v:relnum == 0 ? v:lnum : v:relnum}  ]] -- status column format
vim.o.fillchars = "eob: " -- remove ~ from status column trailing empty space
vim.o.clipboard = "unnamedplus" -- allow copy pasting from yanking and system clipboard
vim.o.wrap = false
vim.o.linebreak = true
vim.o.autoindent = true
vim.o.ignorecase = true
vim.o.smartcase = true
vim.o.shiftwidth = 2
vim.o.tabstop = 2
vim.o.softtabstop = 2
vim.o.expandtab = true
vim.o.undofile = true
vim.o.inccommand = "split"
vim.o.list = true
vim.o.listchars = "tab:  ,lead: ,trail:•,nbsp:•"
vim.o.splitbelow = true
vim.o.splitright = true
vim.o.cursorline = true
vim.o.hlsearch = true
vim.o.conceallevel = 2
vim.o.sessionoptions = "buffers,curdir,folds,winsize,terminal"
vim.o.splitkeep = "screen"
vim.o.laststatus = 3
vim.o.foldmethod = "expr"
vim.o.foldexpr = "v:lua.vim.treesitter.foldexpr()"
vim.o.foldenable = true
vim.o.foldtext = ""
vim.o.foldlevel = 99
vim.o.foldcolumn = "1"
-- vim.o.winbar = "%f %m"
-- vim.opt.winbar = '%{%v:lua.require("ui.winbar")()%}'
