return {
	"nvimdev/dashboard-nvim",
	event = "VimEnter",
	lazy = false,
	opts = {
		theme = "doom",
		config = {
			header = {
				"⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⡀⠀⠀⠀⠀⢀⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀ ",
				"⠀⠀⠀⠀⠀⠀⠀⠀⠀⣠⡖⠁⠀⠀⠀⠀⠀⠀⠈⢲⣄⠀⠀⠀⠀⠀⠀⠀⠀⠀ ",
				"⠀⠀⠀⠀⠀⠀⠀⠀⣼⡏⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢹⣧⠀⠀⠀⠀⠀⠀⠀⠀ ",
				"⠀⠀⠀⠀⠀⠀⠀⣸⣿⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⣿⣇⠀⠀⠀⠀⠀⠀⠀ ",
				"⠀⠀⠀⠀⠀⠀⠀⣿⣿⡇⠀⢀⣀⣤⣤⣤⣤⣀⡀⠀⢸⣿⣿⠀⠀⠀⠀⠀⠀⠀ ",
				"⠀⠀⠀⠀⠀⠀⠀⢻⣿⣿⣔⢿⡿⠟⠛⠛⠻⢿⡿⣢⣿⣿⡟⠀⠀⠀⠀⠀⠀⠀ ",
				"⠀⠀⠀⠀⣀⣤⣶⣾⣿⣿⣿⣷⣤⣀⡀⢀⣀⣤⣾⣿⣿⣿⣷⣶⣤⡀⠀⠀⠀⠀ ",
				"⠀⠀⢠⣾⣿⡿⠿⠿⠿⣿⣿⣿⣿⡿⠏⠻⢿⣿⣿⣿⣿⠿⠿⠿⢿⣿⣷⡀⠀⠀ ",
				"⠀⢠⡿⠋⠁⠀⠀⢸⣿⡇⠉⠻⣿⠇⠀⠀⠸⣿⡿⠋⢰⣿⡇⠀⠀⠈⠙⢿⡄⠀ ",
				"⠀⡿⠁⠀⠀⠀⠀⠘⣿⣷⡀⠀⠰⣿⣶⣶⣿⡎⠀⢀⣾⣿⠇⠀⠀⠀⠀⠈⢿⠀ ",
				"⠀⡇⠀⠀⠀⠀⠀⠀⠹⣿⣷⣄⠀⣿⣿⣿⣿⠀⣠⣾⣿⠏⠀⠀⠀⠀⠀⠀⢸⠀ ",
				"⠀⠁⠀⠀⠀⠀⠀⠀⠀⠈⠻⢿⢇⣿⣿⣿⣿⡸⣿⠟⠁⠀⠀⠀⠀⠀⠀⠀⠈⠀ ",
				"⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣼⣿⣿⣿⣿⣧⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀ ",
				"⠀⠀⠀⠐⢤⣀⣀⢀⣀⣠⣴⣿⣿⠿⠋⠙⠿⣿⣿⣦⣄⣀⠀⠀⣀⡠⠂⠀⠀⠀ ",
				"⠀⠀⠀⠀⠀⠈⠉⠛⠛⠛⠛⠉⠀⠀⠀⠀⠀⠈⠉⠛⠛⠛⠛⠋⠁⠀⠀⠀⠀⠀ ",
				"                               ",
				"          Angel Rada           ",
				"                               ",
			},
			center = {
				{
					icon = " ",
					desc = "[L]azy plugin manager",
					group = "@property",
					action = "Lazy",
					key = "l",
					desc_hl = "String",
					key_hl = "Number",
					icon_hl = "group",
				},
				{
					icon = " ",
					desc = "[M]ason",
					group = "@property",
					action = "Mason",
					key = "m",
					desc_hl = "String",
					key_hl = "Number",
					icon_hl = "group",
				},
				{
					icon = " ",
					desc = "[C]heckhealth",
					group = "@property",
					action = "checkhealt",
					key = "c",
					desc_hl = "String",
					key_hl = "Number",
					icon_hl = "group",
				},
				{
					icon = "󰊳 ",
					desc = "[O]pen last session                  ",
					key = "o",
					action = 'lua require("persistence").load()',
					desc_hl = "String",
					key_hl = "Number",
					icon_hl = "group",
				},
				-- {
				-- 	icon = " ",
				-- 	desc = "[P]rojecs",
				-- 	key = "p",
				-- 	action = "NeovimProjectDiscover",
				-- 	desc_hl = "String",
				-- 	key_hl = "Number",
				-- 	icon_hl = "group",
				-- },
				{
					icon = "󰿅 ",
					desc = "[Q]uit",
					key = "q",
					action = "qa!",
					desc_hl = "String",
					key_hl = "Number",
					icon_hl = "group",
				},
			},
			footer = {},
			vertical_center = true,
			plugins = true,
			-- mru = { enable = false },
			-- project = { enable = false },
		},
	},
	dependencies = { { "nvim-tree/nvim-web-devicons" } },
}
