tab_bar_filter session:~ or session:^$
# map f5 save_as_session --relocatable --use-foreground-process --match=session:.
map ctrl+a>n goto_session 1
map ctrl+a>p goto_session -1

map ctrl+a>s goto_session --sort-by=alphabetical
map ctrl+a>. goto_session ~/.dotfiles/dotfiles.kitty-session
# map ctrl+a>w goto_session ~/Developer/Projects/wear/wear.kitty-session
# map ctrl+a>j goto_session ~/Developer/Projects/joyward/joyward.kitty-session
# map ctrl+a>g goto_session ~/Developer/Projects/personal/games/games.kitty-session
# map ctrl+a>e goto_session ~/Developer/Projects/personal/e-commerce/e-commerce-cna.kitty-session
# map ctrl+a>l goto_session ~/Developer/Projects/load2day/l2d.kitty-session
# map ctrl+a>t goto_session ~/Developer/Projects/personal/tracker/tracker.kitty-session
# map ctrl+a>p goto_session ~/Developer/Projects/personal/promotions/promotions.kitty-session
